### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#299]
Application is down

**Comment by JMurphyWeb** [comment]
```
2017-06-06T08:39:16.374081+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-06T08:39:17.000000+00:00 app[api]: Build started by user jmurphy.web@gmail.com
2017-06-06T08:39:22.651896+00:00 heroku[web.1]: Starting process with command `MIX_ENV=prod mix phoenix.server`
2017-06-06T08:39:28.729182+00:00 app[web.1]: 08:39:28.728 [info] Application karma exited: Karma.start(:normal, []) returned an error: shutdown: failed to start child: Karma.Endpoint
2017-06-06T08:39:28.729235+00:00 app[web.1]:     ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Server
2017-06-06T08:39:28.729243+00:00 app[web.1]:         ** (EXIT) an exception was raised:
2017-06-06T08:39:28.729250+00:00 app[web.1]:             ** (ArgumentError) could not start Cowboy adapter, missing option :key/:keyfile
2017-06-06T08:39:28.729251+00:00 app[web.1]:                 (plug) lib/plug/adapters/cowboy.ex:245: Plug.Adapters.Cowboy.fail/1
2017-06-06T08:39:28.729257+00:00 app[web.1]:                 (plug) lib/plug/adapters/cowboy.ex:211: Plug.Adapters.Cowboy.assert_ssl_options/1
2017-06-06T08:39:28.729258+00:00 app[web.1]:                 (plug) lib/plug/adapters/cowboy.ex:165: Plug.Adapters.Cowboy.normalize_cowboy_options/2
2017-06-06T08:39:28.729259+00:00 app[web.1]:                 (plug) lib/plug/adapters/cowboy.ex:49: Plug.Adapters.Cowboy.args/4
2017-06-06T08:39:28.729259+00:00 app[web.1]:                 (plug) lib/plug/adapters/cowboy.ex:137: Plug.Adapters.Cowboy.child_spec/4
2017-06-06T08:39:28.729269+00:00 app[web.1]:                 (phoenix) lib/phoenix/endpoint/cowboy_handler.ex:82: Phoenix.Endpoint.CowboyHandler.child_spec/3
2017-06-06T08:39:28.729269+00:00 app[web.1]:                 (phoenix) lib/phoenix/endpoint/server.ex:17: anonymous fn/5 in Phoenix.Endpoint.Server.init/1
2017-06-06T08:39:28.729270+00:00 app[web.1]:                 (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
2017-06-06T08:39:30.249462+00:00 app[web.1]: {"Kernel pid terminated",application_controller,"{application_start_failure,karma,{{shutdown,{failed_to_start_child,'Elixir.Karma.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Phoenix.Endpoint.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<\"could not start Cowboy adapter, missing option :key/:keyfile\">>},[{'Elixir.Plug.Adapters.Cowboy',fail,1,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,245}]},{'Elixir.Plug.Adapters.Cowboy',assert_ssl_options,1,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,211}]},{'Elixir.Plug.Adapters.Cowboy',normalize_cowboy_options,2,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,165}]},{'Elixir.Plug.Adapters.Cowboy',args,4,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,49}]},{'Elixir.Plug.Adapters.Cowboy',child_spec,4,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,137}]},{'Elixir.Phoenix.Endpoint.CowboyHandler',child_spec,3,[{file,\"lib/phoenix/endpoint/cowboy_handler.ex\"},{line,82}]},{'Elixir.Phoenix.Endpoint.Server','-init/1-fun-0-',5,[{file,\"lib/phoenix/endpoint/server.ex\"},{line,17}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1755}]}]}}}}},{'Elixir.Karma',start,[normal,[]]}}}"}
2017-06-06T08:39:30.257121+00:00 app[web.1]: Kernel pid terminated (application_controller) ({application_start_failure,karma,{{shutdown,{failed_to_start_child,'Elixir.Karma.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Phoenix.Endpoint.Ser
2017-06-06T08:39:30.257376+00:00 app[web.1]:
2017-06-06T08:39:31.584864+00:00 app[web.1]: Crash dump is being written to: erl_crash.dump...done
2017-06-06T08:39:31.677049+00:00 heroku[web.1]: Process exited with status 1
2017-06-06T08:39:31.692547+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by JMurphyWeb** [comment]
https branch causing the issue
