### ISSUE TITLE
Testing bug using coveralls

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#73]
I get an error when running `mix coveralls.html`
```
09:59:00.916 [error] Task #PID<0.836.0> started from #PID<0.834.0> terminating
** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.

The error is :no_more_hosts

More detail below:

{:permanent_failure, "email-smtp.eu-west-1.amazonaws.com", "554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: contractor@gmail.com\r\n"}

    lib/bamboo/adapters/smtp_adapter.ex:74: Bamboo.SMTPAdapter.handle_response/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.115485522/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []
09:59:00.956 [error] Task #PID<0.861.0> started from #PID<0.859.0> terminating
** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.

The error is :no_more_hosts

More detail below:

{:permanent_failure, "email-smtp.eu-west-1.amazonaws.com", "554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: different@test.com\r\n"}

    lib/bamboo/adapters/smtp_adapter.ex:74: Bamboo.SMTPAdapter.handle_response/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.115485522/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []

```

Which doesn't appear when running `mix test`

**Comment by JMurphyWeb** [comment]
It seems like our bamboo mocking mechanism is being overwritten when running `mix coveralls.html`

This error has only appeared after I added some emailing sending functionality as part of #72

**Comment by JMurphyWeb** [comment]
We will mock all email sending for now
